// packages/vue/lib/components/Button.vue
<script setup lang="ts">
import styles from '../styles.module.css'

interface Props {
  backgroundColor?: string,
  color?: string,
  borderColor?: string,
}

withDefaults(defineProps<Props>(), {
  backgroundColor: 'white',
  color: 'black',
  borderColor: 'black',
})
</script>

<template>
  <button :class="styles.button" :style="{
    backgroundColor,
    color,
    borderColor
  }">
    <slot>Button</slot>
  </button>
</template>

// packages/react/lib/components/Button.tsx
import styles from '../styles.module.css'

export function Button({
  backgroundColor = 'white',
  color = 'black',
  borderColor = 'black',
  children = 'Button',
}: {
  backgroundColor?: string,
  color?: string,
  borderColor?: string,
  children?: React.ReactNode
}) {
  return (
    <button
      className={`${styles.button}`}
      style={{
        backgroundColor,
        color,
        borderColor
      }}
    >
      {children}
    </button>
  )
}
