// packages/vue/lib/components/Paragraph.vue
<script setup lang="ts">
import styles from '../styles.module.css'

interface Props {
    textAlign?: 'left' | 'center' | 'right' | 'justify'
}

withDefaults(defineProps<Props>(), {
    textAlign: 'left'
})
</script>

<template>
    <p :class="styles.p" :style="{
        textAlign
    }">
        <slot></slot>
    </p>
</template>

// packages/react/lib/components/Paragraph.tsx
import styles from '../styles.module.css'

export function P({
    textAlign = 'left',
    children
}: {
    textAlign?: 'left' | 'center' | 'right' | 'justify'
    children: React.ReactNode
}) {
    return <p
        className={`${styles.p}`}
        style={{
            textAlign
        }}
    >
        {children}
    </p>
}
