// packages/react/lib/components/Image.tsx
import styles from '../styles.module.css'

export function Image({
  width = 'auto',
  height = 'auto',
  aspectRatio = 1,
}: {
  width?: number | string,
  height?: number | string,
  aspectRatio?: number,
}) {
  return (
    <div
      className={`${styles.image}`}
      style={{
        width,
        height,
        aspectRatio,
      }} />
  )
}

// packages/vue/lib/components/Image.vue
<script setup lang="ts">
import styles from '../styles.module.css'

interface Props {
  width?: number | string,
  height?: number | string,
  aspectRatio?: number,
}

withDefaults(defineProps<Props>(), {
  width: 'auto',
  height: 'auto',
  aspectRatio: 1,
})
</script>

<template>
  <div :class="styles.image" :style="{
    width,
    height,
    aspectRatio,
  }"></div>
</template>
